spring:
  config:
    activate:
      on-profile: docker
  application:
    name: user
  kafka:
    bootstrap-servers: kafka:9093
  data:
    mongodb:
      auto-index-creation: true
      authentication-database: admin
      username: user
      password: password
      database: buy01
      port: 27017
      host: mongodb

eureka:
  client:
    serviceUrl:
      defaultZone: http://registery:8761/eureka/

application:
  security:
    jwt:
      key-id: user-service-key
      issuer: http://user
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000
server:
  port: 9001

media:
  upload:
    base:
      dir: '/app/uploads'
    max:
      file:
        size: 2097152
  allowed:
    content:
      types: image/jpeg,image/png,image/webp
