spring:
  config:
    activate:
      on-profile: prod
  application:
    name: users
  kafka:
    bootstrap-servers: 172.20.0.1:9092
  data:
    mongodb:
      auto-index-creation: true
      uri: mongodb://rootuser:password@172.20.0.1:27017/buy01?authSource=admin
      authentication-database: admin

eureka:
  client:
    service-url:
      defaultZone: http://172.20.0.1:8761/eureka/

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days

server:
  port: 8083

media:
  upload:
    base:
      dir: '/app/uploads'  # Changed for Docker environment
    max:
      file:
        size: 2097152
  allowed:
    content:
      types: image/jpeg,image/png,image/webp
