spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

#
#spring:
#  application:
#    name: products
#
#  kafka:
#    bootstrap-servers: localhost:9092
#
#
#  data:
#    mongodb:
#      authentication-database: admin
#      username: rootuser
#      password: password
#      database: buy01
#      port: 27017
#      host: localhost
#      auto-index-creation: true
#
#server:
#  port: 8084
