
spring:
  application:
    name: products

  kafka:
    bootstrap-servers: localhost:9092
#    consumer:
#      group-id: auth-group
#      auto-offset-reset: earliest
#      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
#      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
#      properties:
#        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
#        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
#        spring.json.trusted.packages: "com.zone01.products.utils,com.zone01.users.utils,com.zone01.*"
#        spring.json.type.mapping: response:com.zone01.products.utils.Response
#        spring.json.value.default.type: com.zone01.products.utils.Response
#    producer:
#        key-serializer: org.apache.kafka.common.serialization.StringSerializer
#        value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
#        properties:
#          spring.json.type.mapping: response:com.zone01.products.utils.Response
#          reply-timeout: 30000

  data:
    mongodb:
      authentication-database: admin
      username: rootuser
      password: password
      database: letsplay
      port: 27017
      host: localhost
      auto-index-creation: true

server:
  port: 8084
