spring:
  application:
    name: order-service

  security:
    oauth2:
      client:
        registration:
          order-service:
            client-id: order-service
            client-secret: ${USER_SERVICE_PASSWORD}
            authorization-grant-type: client_credentials
            scope: server
            provider: custom-provider
        provider:
          custom-provider:
            token-uri: http://localhos:9001/api/v1/auth-service/oauth/token # auth-service

  kafka:
    bootstrap-servers: localhost:9092
  data:
    mongodb:
      auto-index-creation: true
      authentication-database: admin
      username: user
      password: ${MONGODB_PASSWORD}
      database: buy01
      port: 27017
      host: localhost

server:
  servlet:
    context-path: /api/v1/order
  port: 9005