
spring:
  config:
    activate:
      on-profile: docker
  application:
    name: order

  kafka:
    bootstrap-servers: 172.20.0.1:9092

  data:
    mongodb:
      authentication-database: admin
      uri: mongodb://user:password@172.20.0.1:27017/buy01?authSource=admin
      auto-index-creation: true

payduya:
  main-key:   'pNzWmqne-WMXi-CDFX-neqK-IAV9hna1RIJ7'
  production:
    public-key: 'live_public_qTyUL2O1YCIA5jb3FLmGZDWi5fl'
    private-key:  'live_private_8o8fjQhyq2LXaJ3fF0GuPaT7CjL'
    token:  'WAdUvY3jsvMGMOLc2Dro'

eureka:
  client:
    service-url:
      defaultZone: http://172.20.0.1:8761/eureka/

server:
  port: 9004
