spring:
  application:
    name: media
  data:
    mongodb:
      authentication-database: admin
      username: rootuser
      password: password
      database: letsplay
      port: 27017
      host: localhost
      auto-index-creation: true

server:
  port: 8085