spring:
  config:
    activate:
      on-profile: docker
  application:
    name: gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:4200"
              - "https://localhost:4200"
              - "https://front-end:4200"
              - "http://front-end:4200"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true

      routes:
        - id: user
          uri: http://user:9001
          predicates:
            - Path=/api/v1/user/**
        - id: product
          uri: http://product:9002
          predicates:
            - Path=/api/v1/product/**
        - id: media
          uri: http://media:9003
          predicates:
            - Path=/api/v1/media/**
        - id: order
          uri: http://order:9004
          predicates:
            - Path=/api/v1/order/**
server:
  port: 9000
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: password
    key-store-type: PKCS12
    key-alias: gateway

eureka:
  client:
    serviceUrl:
      defaultZone: http://registery:8761/eureka/

logging:
  level:
    org.springframework.boot.ssl: DEBUG
    org.springframework.web.cors: DEBUG
    org.springframework.web.reactive.cors: DEBUG