version: "3.8"

services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DOCKER_GROUP_ID: "${DOCKER_GROUP_ID:-999}"
    container_name: jenkins
    ports:
      - "8080:8080"  # Jenkins web interface
      - "50000:50000"  # Jenkins agent port (optional)
    volumes:
      - jenkins_home:/var/jenkins_home  # Persistent Jenkins data
      - /var/run/docker.sock:/var/run/docker.sock  # Allow Jenkins to use Docker
    user: "jenkins"  # Run Jenkins as jenkins user
    restart: unless-stopped
    networks:
      - backend

volumes:
  data:
  jenkins_home:

networks:
  backend:
    driver: bridge
